FROM apache/airflow:2.8.4-python3.11

USER airflow

COPY requirements.txt /requirements.txt
RUN pip install --no-cache-dir -r /requirements.txt

COPY dags/ /opt/airflow/dags/
COPY src/ /opt/airflow/src/
COPY data/ /opt/airflow/data/
COPY models/ /opt/airflow/models/

ENV AIRFLOW__CORE__LOAD_EXAMPLES=False
ENV AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION=False

ENV AIRFLOW__CORE__EXECUTOR=SequentialExecutor

ENV AIRFLOW__CORE__FERNET_KEY=""